Data review / MongoDB / Docker
MediaComem/open-co2 pull request #3
Opened 2022-05-05 07:14 UTC by jfavlam

## Quickstart local setup

- `git clone git@github.com:MediaComem/open-co2.git`
- `cd open-co2/server`
- `docker-compose up -d`

Default GQL endpoint is available at http://localhost:4000/graphql

Query example using Apollo Studio (getCategoryByName):
```
query getCategoryByName($name: String!) {
  getCategoryByName(name: $name) {
    title
    fullPath
  }
}
```
Variable:
```
{
  "name": "freight_train"
}
```

---

## Main features/fix

- Setup XLS source file (https://docs.google.com/spreadsheets/d/168Gjlb9d5b_0Vb4q1IeKWGPGBIEcD6oo0ggLZafygwY)
- Seeder to process XLS file
- Persist data in DB (MongoDB)
- Review GraphQL types definition
- Start resolver refactor to get data from DB (all units, all categories, category by name)
- Review project structure (/server/app + /server/seeder)
- Dockerizing project
  - Seed data
  - Populate MongoDB
- GraphQL Playground service in stack (as Apollo alternative) - At http://localhost:4200 by default
- Open CO2 server landing page – At http://localhost:4000 by default

Notes/Missing:
- Resolver and available API queries are incomplete at this stage
- co2eq model will be review to calculate confidence index in mean values + categories with different children units will be ignored

2022-05-05 10:37 UTC, slecorne requested changes
I put quite a few comments on naming, we can discuss if it really make sense or not

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileComposer/fileComposer.js
> +          delete row[`Level ${n + 1}`];
Not sure but I would say the level is n+1
```suggestion
        const currentLevel = n+1;
        const key = `Level ${currentLevel }`;
        if (row[key] !== undefined) {
          // Add title key with value from level
          row.title = row[key];
          // Add depth key from level number
          row.depth = parseInt(currentLevel);
          // Delete unused level key
          delete row[key];
          break;
```

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileComposer/fileComposer.js
> +    this.#updateKeys();
```suggestion
    this.#parseRows();
```

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileComposer/fileComposer.js
> +    const deepTree = this.#getDeepTree();
avoid parsing the tree multiple times. Do once after ParseRows and store in private var

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileComposer/fileComposer.js
> +    this.sheet = sheet;
```suggestion
   * @param {Sheet content from fileReader} rows
   */
  constructor(rows) {
    this.rows= rows;
```

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileReader/fileReader.js
> +export default class FileReader {
```suggestion
export default class XLSDataReader{
```

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileComposer/fileComposer.js
> +export default class FileComposer {
```suggestion
export default class DataParser{
```

2022-05-05 10:37 UTC, slecorne commented on server/seeder/modules/fileComposer/fileComposer.js
> +  }
really hard to follow, I will check if I can help to make it more readable

2022-05-06 15:37 UTC, jfavlam commented on server/seeder/modules/fileComposer/fileComposer.js
> +    const deepTree = this.#getDeepTree();
Very good point, especially with this function 👍

2022-05-09 13:59 UTC, jfavlam commented on server/seeder/modules/fileComposer/fileComposer.js
> +          delete row[`Level ${n + 1}`];
row[key] https://usbeketrica.com/media/83950/download/rocky2.jpg?v=1&inline=1

2022-05-10 08:55 UTC, merged